/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiculesRouteImport } from './routes/vehicules'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TransitRouteImport } from './routes/transit'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as DevisRouteImport } from './routes/devis'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CataloguesRouteImport } from './routes/catalogues'
import { Route as IndexRouteImport } from './routes/index'

const VehiculesRoute = VehiculesRouteImport.update({
  id: '/vehicules',
  path: '/vehicules',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const TransitRoute = TransitRouteImport.update({
  id: '/transit',
  path: '/transit',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisRoute = DevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CataloguesRoute = CataloguesRouteImport.update({
  id: '/catalogues',
  path: '/catalogues',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogues': typeof CataloguesRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/equipe': typeof EquipeRoute
  '/transit': typeof TransitRoute
  '/transport': typeof TransportRoute
  '/vehicules': typeof VehiculesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogues': typeof CataloguesRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/equipe': typeof EquipeRoute
  '/transit': typeof TransitRoute
  '/transport': typeof TransportRoute
  '/vehicules': typeof VehiculesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogues': typeof CataloguesRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/equipe': typeof EquipeRoute
  '/transit': typeof TransitRoute
  '/transport': typeof TransportRoute
  '/vehicules': typeof VehiculesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogues'
    | '/contact'
    | '/devis'
    | '/equipe'
    | '/transit'
    | '/transport'
    | '/vehicules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogues'
    | '/contact'
    | '/devis'
    | '/equipe'
    | '/transit'
    | '/transport'
    | '/vehicules'
  id:
    | '__root__'
    | '/'
    | '/catalogues'
    | '/contact'
    | '/devis'
    | '/equipe'
    | '/transit'
    | '/transport'
    | '/vehicules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CataloguesRoute: typeof CataloguesRoute
  ContactRoute: typeof ContactRoute
  DevisRoute: typeof DevisRoute
  EquipeRoute: typeof EquipeRoute
  TransitRoute: typeof TransitRoute
  TransportRoute: typeof TransportRoute
  VehiculesRoute: typeof VehiculesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicules': {
      id: '/vehicules'
      path: '/vehicules'
      fullPath: '/vehicules'
      preLoaderRoute: typeof VehiculesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transit': {
      id: '/transit'
      path: '/transit'
      fullPath: '/transit'
      preLoaderRoute: typeof TransitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis': {
      id: '/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof DevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogues': {
      id: '/catalogues'
      path: '/catalogues'
      fullPath: '/catalogues'
      preLoaderRoute: typeof CataloguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CataloguesRoute: CataloguesRoute,
  ContactRoute: ContactRoute,
  DevisRoute: DevisRoute,
  EquipeRoute: EquipeRoute,
  TransitRoute: TransitRoute,
  TransportRoute: TransportRoute,
  VehiculesRoute: VehiculesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
